const { createPost, listPost } = require('./Controllers/Post_Controller')
const { getUser, createUser, login, jwtVerify, getUsers, deleteUser, setEndereco, getEndereco } = require('./Controllers/User_Controller')
const {getLikes, setLikes} = require('./Controllers/Likes_Controller')
const { setComentarios } = require('./Controllers/Comentarios_Controller')
const Routes = require('express').Router()

Routes.get('/',getUsers)
Routes.post('/createUser',createUser)
Routes.post('/login',login)
Routes.get('/getLikes',getLikes)
Routes.post('/setLikes',setLikes)
Routes.post('/createPostagem',createPost)
Routes.get('/listPost',listPost)
Routes.get('/listUsers',getUsers)
Routes.post('/getUser',jwtVerify,getUser)
Routes.post('/setComentarios',setComentarios)
Routes.delete("/deleteUser",deleteUser)
Routes.post("/setEndereco",setEndereco)
Routes.get("/getEndereco",getEndereco)
module.exports = Routes